<a href="https://colab.research.google.com/github/vipin0761/Data_Science/blob/main/pandas_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

###  All Pandas data structures are value mutable (can be changed) and except Series all are size mutable. Series is size immutable.

In [ ]:
df = pd.read_csv("services.csv") # read csv files
df2 = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")  # reading from a remote server
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx") # read excel files
df.head(3) # to read first n rows of the data default is 5
df.tail(3) # to read last n rows of the data default is 5

In [ ]:
import lxml
import pandas as pd
url_data = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html") #  read data from html sites

In [ ]:
df3.to_csv("players_data.csv",index=False) # write data to csv

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [ ]:
df['status']  # access a column in the table as a series ( which is equivalent to a list)
list(df['status'])
type(df['status'])

pandas.core.series.Series

In [ ]:
df[['status']]  # access a column in the table as a data frame
type(df[['status']])

pandas.core.frame.DataFrame

In [ ]:
df[['email','keywords','name']] # access a set of columns in the table as a data frame

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df.dtypes # show data types of each column

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [2]:
df.describe() # basic statistical analysis of numerical columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.dtypes == 'object' # all columns with object data

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
df.dtypes[df.dtypes == 'object'].index # all columns headings object data

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
df[df.dtypes[df.dtypes == 'object'].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [5]:
df[df.dtypes[df.dtypes == 'float64'].index].head(3)

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250

In [6]:
df[df.dtypes[df.dtypes == 'int64'].index].head(3)

   PassengerId  Survived  Pclass  SibSp  Parch
0            1         0       3      1      0
1            2         1       1      1      0
2            3         1       3      0      0

In [ ]:
df[['Ticket','Cabin']][4:11:2] # slicing in data frame

     Ticket Cabin
4    373450   NaN
6     17463   E46
8    347742   NaN
10  PP 9549    G6

In [ ]:
df['new_col'] = 0 # adding a new column with 0 value for each row

In [ ]:
df["new_col1"] = df['PassengerId'] + df['Pclass'] # creating a new column by combining existing columns

In [ ]:
pd.Categorical(df['Pclass'])  # analysing categorical data

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [ ]:
df['Cabin'].unique() # list of unique values in a column

In [7]:
len(df[df['Age'] >18])

575

In [8]:
df[df['Age'] >18].head(3) # records where age > 18

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
df[(df['Sex'] == 'female')  & (df['Fare'] > 32 )].head(3) # multiple filters with and

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C

In [11]:
df[(df['Sex'] == 'felmale')  | (df['Fare'] > 32 )].head(3) # multiple filters with or

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [ ]:
df[df['Fare'] == max(df['Fare'])]['Name'] # specific column with max fare

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [ ]:
df.iloc[0:2,[0,1,2]] # iloc is used to extract specific row and clo number combination -- iloc[r_start:r_end, [col1,co2... coln]]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1

In [ ]:
df.loc[0:2,['PassengerId','Survived','Pclass']]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3